let
  sources = import ./nix/sources.nix; # sources.nix was generated by niv
  pkgs = import sources.nixpkgs { };
  nixfiles = import sources.nixfiles { };
  neovim = nixfiles.neovim {
    pkgs = pkgs;
    withOCaml = true;
    withWriting = true;
  };
in
pkgs.mkShell
{
  # nix-shell runs shell hooks at start
  shellHooks = ''
    alias vim='nvim'
  '';

  # lists all packages in development environment
  buildInputs = with pkgs; [
    bash
    neovim
  ];
}
